feat: 공통 컴포넌트 세팅
FINALALT1/money-bridge pull request #21
Opened 2023-06-07 12:05 UTC by hyeon17

## 📌 관련 이슈
closed #3 

## ✨ 과제 내용
conf: enum 작성
feat: 공통 컴포넌트 세팅
feat: 권한 전역 상태 추가

2023-06-07 13:27 UTC, yousunzoo commented on src/components/common/Card/PostCard.tsx
> +function PostCard({ props }: any) {
해당 컴포넌트는 PostCardList로 이름을 바꿔주시고, map 함수 안에 있는 요소들은 PostCardItem으로 묶어서 별도의 컴포넌트로 제작해주세요~!

2023-06-08 04:12 UTC, hyeon17 commented on src/components/common/Card/PostCard.tsx
> +function PostCard({ props }: any) {
넵 수정했습니다!

2023-06-08 06:14 UTC, kjungit requested changes
수정사항 전달드립니다. 확인부탁드립니다!

2023-06-08 06:14 UTC, kjungit commented on src/components/common/CardItem/PbCardItem.tsx
> +function PbCardItem({ key, router }: any) {
변수명 key보다는 item으로 하거나 구조분해를 통해서 들고오면 코드가 더 가시성있고 깔끔해질거 같아요!

2023-06-08 06:14 UTC, kjungit commented on src/components/common/CardItem/PbCardItem.tsx
> +      <div className="mx-auto my-4 flex flex-col h-48 w-4/5 rounded-xl shadow-md" key={key?.id}>
key?에 전체에 해당하는 내용인데 ?는 없어도 될 것같아요! 카드리스트에서 map을 돌릴때 item이 없으면 사용되지 않기 때문에요! 확인해보시고 수정하시면 될 것 같습니다!

2023-06-08 06:14 UTC, kjungit commented on src/components/common/CardItem/PbCardItem.tsx
> +            <div>{key?.name}이름</div>
이것 또한 전체적으로 반영되는 내용인데 /{key?.name} 이름/이 아닌 /이름 {key.name}/ 이 순서로 전체적으로 수정되어야 할것 같습니다!

2023-06-08 06:14 UTC, kjungit commented on src/components/common/CardItem/PbCardItem.tsx
> +function PbCardItem({ key, router }: any) {
router는 혹시 왜 받아온걸까요!? 안에서 선언하거나 사용하는곳이 어딘지 확인해주세요!

2023-06-08 06:18 UTC, yousunzoo requested changes

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/Button/FixedButton.tsx
> +    <div className="flex h-full w-full items-end">
하단에 고정시키는 코드가 필요합니다!
고정시킬 때는 하단 네비게이션바가 있기 때문에 해당 부분만큼은 띄워두고 고정시켜주세요~! ☺️

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/CardItem/PbCardItem.tsx
> +  const [isBookmark, setIsBookmark] = useState(false);
isBookmark는 props로부터 전달받아야 하기 때문에 초기값을 key.isBookmark로 지정해야 합니다!

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/CardItem/PbCardItem.tsx
> +      <div className="mx-auto my-4 flex flex-col h-48 w-4/5 rounded-xl shadow-md" key={key?.id}>
key는 map 함수 안에서 쓰이는 것이기 떄문에 여기 말고 PbCardList.tsx에서 <PbCardItem key={item.id} />로 표기해주시면 되구요!
PbCardList는 ul 태그로, PbCardItem은 div가 아닌 li 태그로 변경해주세요!
그리고 li라는 하나의 태그로 아래의 요소들을 모두 감싸고 있는 상황이라면, `<></>`로 감싸줄 필요가 없습니다!

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/CardList/PbCardList.tsx
> +function PbCardList({ props }: any) {
props를 통째로 들고 오시는거라면, 중괄호로 감싸주실 필요가 없습니다!

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/CardList/PostCardList.tsx
> +        props.map((item: any) => <PostCardItem key={item} router={router} />)
map 함수에서 key는 리스트 안에서 해당 카드를 찾기 쉽도록 유니크한 값으로 지정해주고, 실제 브라우저에는 적용이 되지 않는 값입니다.
주로 key는 해당 아이템의 id 값을 사용합니다.
key={item.id}로 바꿔주시고, PostCardItem에 props를 내려주실 땐 key가 아닌 다른 이름으로 내려주셔야 합니다!

2023-06-08 06:18 UTC, yousunzoo commented on src/components/common/CardItem/PbCardItem.tsx
> +          <button onClick={() => router.push(`/detailPage/${key?.id}`)}>정보보기</button>
onClick 등 이벤트 핸들러 함수에 들어가는 함수는 별도의 함수로 만들어 작성해주시는게 유지보수와 가독성 면에서 더 좋을 것 같습니다!

2023-06-08 06:19 UTC, yousunzoo commented on src/components/common/CardItem/PbCardItem.tsx
> +  const [isBookmark, setIsBookmark] = useState(false);
또한 로그인하지 않은 상태에서는 북마크가 아예 없기 때문에 이부분도 고려해주셔야 할 것 같습니다!

2023-06-08 07:00 UTC, merged

2023-06-08 07:02 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +function PbCardItem({ key, router }: any) {
수정했습니다!

2023-06-08 07:02 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +      <div className="mx-auto my-4 flex flex-col h-48 w-4/5 rounded-xl shadow-md" key={key?.id}>
수정했습니다!

2023-06-08 07:02 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +            <div>{key?.name}이름</div>
수정했습니다!

2023-06-08 07:09 UTC, hyeon17 commented on src/components/common/Button/FixedButton.tsx
> +    <div className="flex h-full w-full items-end">
수정했습니다!

2023-06-08 07:11 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +      <div className="mx-auto my-4 flex flex-col h-48 w-4/5 rounded-xl shadow-md" key={key?.id}>
수정했습니다!

2023-06-08 07:11 UTC, hyeon17 commented on src/components/common/CardList/PbCardList.tsx
> +function PbCardList({ props }: any) {
수정했습니다!

2023-06-08 07:12 UTC, hyeon17 commented on src/components/common/CardList/PostCardList.tsx
> +        props.map((item: any) => <PostCardItem key={item} router={router} />)
수정했습니다!

2023-06-08 07:12 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +          <button onClick={() => router.push(`/detailPage/${key?.id}`)}>정보보기</button>
수정했습니다!

2023-06-08 07:13 UTC, hyeon17 commented on src/components/common/CardItem/PbCardItem.tsx
> +  const [isBookmark, setIsBookmark] = useState(false);
수정했습니다!